### PR TITLE
depend on (and work with) TF 1.14.0 and TFP 0.7.0

### PR DESCRIPTION
**Pull request by goldingn**
These are the latest releases of TF and TFP. There have been enough breaking changes in TFP, and deprecation warnings added to TF that the previous version is incompatible with them. So this fixes those, but is no longer compatible with previous versions.

Getting the correct versions lined up has been very painful, so I'm planning to peg greta to specific version of TF and TFP from now on. This should make managing installation easier too.

The installation suggestion for this version is now simpler, as TFP is on Anaconda

### CODE REVIEW

**Comment by Voltemand** [comment]
Is tfp 0.7 on conda? I was having trouble downloading it from there recently but I might have just been looking for it in the wrong place.

**Comment by goldingn** [comment]
Shit, yeah I thought I had the basic installation working, but apparently not.

Looks like the GitHub version of r tensorflow now installs TFP 0.7.0 by default with version 1.14, is fine if you specify to install tfp, but goes awry if you specify to install 0.7.0...

But it looks like this is the best instruction for now, and installs TFP 0.7.0 with on conda, with both the CRAN and GitHub versions of tensorflow
```r
install_tensorflow(version = "1.14", extra_packages = "tensorflow-probability")
```

**Comment by goldingn** [comment]
It doesn't appear to install TFP from conda (you're right, seems like only 0.6.0 up there), but automagically installs it anyway so I'm happy with that!

**Comment by Voltemand** [comment]
Auto-magic is good!

**Comment by Voltemand** [comment]
Is the intention to install with conda by default because I think `install_tensorflow` defaults to virtual_env installation on mac and linux.

**Comment by goldingn** [comment]
`install_tensorflow()` has been automatically using conda to install on my unix machine, when leaving `method = "auto"`. But I think that's because I don't have virtualenv, and it would use that instead if it were there.

I've just pushed a change to add `method = "conda"` if the user has conda. I was a little on the fence, given how fraught the installation has been, but I think the speedup is worth it.

**Pull request merged**
