### PR TITLE
Feature/simulate

### PR DESCRIPTION
**Pull request by goldingn**
Add a `simulate.greta_model()` function, to simulate parameters and data from a greta model

Also enable `calculate()` to do simulations of named greta arrays, conditional on fixed values of others, with an `nsim` argument (defaulting to `NULL`) for the number of samples.

### CODE REVIEW

**Comment by goldingn** [comment]
There are now lots of tests, documentation, and examples for the expected behaviour. However the calculate() code is currently a mess (copy-pasta between the previous deterministic calculate() and previous simulate() code), and simulate() has been switched to depend on calculate(), so the tests are largely failing.

I have a clear path forward though:
 1. let `dag_class` define each node separately as either forward/sampling, based on whether there are free state values to push through it (for sampling conditional on MCMC samples)
 2. patch up and simplify the code in calculate() to use this new hybrid sampling where appropriate
 3. fix all remaining bugs

I may do a little on this tomorrow, or otherwise next week

**Comment by goldingn** [comment]
😓

**Comment by goldingn** [comment]
🙏

**Comment by goldingn** [comment]
🙌

**Comment by cboettig** [comment]
:tada: :rocket:

**Pull request merged**
