### PR TITLE
first attempt at the touchstone PR - should resolve  #365

### LINKED ISSUE #365: Implement "branchmarking" - benchmarking for PRs in greta
The [touchstone](https://github.com/lorenzwalthert/touchstone) package is still under development, but looks like it provides a simple workflow for comparing speed of different branches.

It looks like STAN has an approach for this, see in [this PR](https://github.com/stan-dev/stan/pull/3033), which is done by [this buildbot](https://github.com/stan-buildbot?tab=overview&from=2021-02-01&to=2021-02-28), or perhaps [here](https://github.com/stan-dev/performance-tests-cmdstan). 

It seems like the touchstone approach might be a bit simpler to implement.

### PR DESCRIPTION
**Pull request by njtierney**

### CODE REVIEW

**Comment by assignUser** [comment]
Hey @njtierney !
The `script.R` failed because {touchstone} does not load your package by default. You can fix this by adding `expr_before_benchmark = library(greta)` to each benchmark (adding this as `expr_before_benchmark` keeps it out of the time of the benchmark )

**Comment by njtierney** [comment]
Heya @assignUser - so that looks like it gets greta loaded, which is great!

However, it looks like it doesn't register the python dependencies: https://github.com/greta-dev/greta/runs/5722364353?check_suite_focus=true#step:2:8444

I'd like to reuse the installation of greta dependencies instead of writing out more code - that is, I wonder if it is possible to ask the action to depend on, or even run the action: [`greta-install-deps`](https://github.com/greta-dev/greta/blob/master/.github/workflows/greta-install-deps.yaml), rather than running code like I have in [R-CMD-check](https://github.com/greta-dev/greta/blob/master/.github/workflows/R-CMD-check.yaml#L59-L96) - if that makes sense?

**Comment by assignUser** [comment]
@njtierney nice!
I don't think it is necessary to add the action, just adding 
```
library(greta)
install_greta_deps(timeout = 50)
``` 
At the top of `script.R` should do it, each benchmark is run in a new callr subprocess but should still have access to the installed python dependencies :)

**Comment by njtierney** [comment]
Hmmm!

https://github.com/greta-dev/greta/runs/5733168332?check_suite_focus=true#step:2:8423

Should have I put the `library` call somewhere else?

**Comment by assignUser** [comment]
Under `branch_install` should work :crossed_fingers:

**Comment by assignUser** [comment]
🚀 The comment workflow did not run because the file needs to be on the repository default branch, after this pr it should work as intended!

**Comment by njtierney** [comment]
Thanks so much, @assignUser ! Looking forward to testing this all out.

**Pull request merged**
