### PR TITLE
make pb_update greater than thin to avoid zero length tensors

### PR DESCRIPTION
**Pull request by jdyen**
I was trying to track down an error that occurs when switching from warmup to sampling. It looks a bit like this:
> Error in py_call_impl(callable, dots$args, dots$keywords): UnimplementedError: TensorArray has size zero, but element shape [?,1] is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.

which I can recreate by setting `thin` >= `pb_update` (i.e. make burst size equal to or less than thinning rate):
`library(greta)`
`x <- normal(0, 1, dim = 1)`
`mod <- model(x)`
`draws <- mcmc(mod, n_samples = 100, warmup = 100, thin = 3, pb_update = 2)`

This PR adds a hacky fix for this. Not sure if this is exactly the original error that sent me down this rabbit-hole because I can't recreate that error and have never explicitly set `pb_update`. Does pb_update get reset anywhere other than `mcmc`?

### CODE REVIEW

**Comment by goldingn** [comment]
Ah, good catch. I think there will be other unidentified bugs with thin - I don't thin during sampling so never really thought about it nor got around to testing it thoroughly. This seems like a sensible thing to do in any case though!

Could you please add a short note to an appropriate place in the helpfile so the user knows they'll be ignored in this situation. Nothing more annoying than your commands being silently ignored by your computer :)

**Comment by jdyen** [comment]
Have updated man file. This sort of error seemed to occur when increasing thinning rate (without setting pb_update) but when there was no reason for pb_update to be the root cause. So might actually be due to how burst size is set rather than pb_update itself.

**Comment by goldingn** [comment]
would you mind bumping up the version (to `0.3.0.9003`) and the date too?

**Comment by jdyen** [comment]
I managed to get the same error in another example where pb_update was not set to a stupidly small value. I think it was caused by setting `one_by_one = TRUE`, which sets `ideal_burst_size` to 1. If `thin` > 1, then this causes an issue in the sampling phase because it's trying to save zero iterations out of each burst. Is that possible? If so, should the burst size be addressed, or the way thinning is handled?

**Comment by goldingn** [comment]
Ah yes, that makes sense. Yes, that's an issue with the way thinning is handled (it's just passed it to tensorflow to deal with), which doesn't work with the stuff we have to do on the R side.
Probably the most sensible thing would be to never thin on the tensorflow side, but to apply thinning to each burst of values after tensorflow has returned them.

That should be fairly simple to implement. we could add a new sampler R6 method `burst_keep()` (like [`burst_lengths()`](https://github.com/greta-dev/greta/blob/master/R/inference_class.R#L512-L534) to return a list of vectors of elements to keep from each burst (this will change between bursts because we need to account for how many were skipped at the end of the last burst), and this could be passed in as an argument to [`run_burst()`](https://github.com/greta-dev/greta/blob/master/R/inference_class.R#L640-L692) and used to subset the output [here](https://github.com/greta-dev/greta/blob/master/R/inference_class.R#L660).

Then we'd just need to add the thinning information to the mcmc.list objects (which isn't currently done) [here](https://github.com/greta-dev/greta/blob/master/R/inference.R#L448-L449)

**Pull request merged**
