### PR TITLE
Add Zero Inflated Distribution

### PR DESCRIPTION
**Pull request by Rosenguyen0411**
Hi,
I was reading the 2nd version of Statistical Rethinking by McElreath (link: https://xcelab.net/rm/sr2/) (password: tempest) and came across the Zero-Inflated Poisson distribution in chapter 12 (Another interesting post about the book, Zero-inflated Poisson model and Greta: https://www.r-bloggers.com/bayesian-models-in-r-2/). McElreath used the Rethinking package which uses Stan as back-end for the model. When I attempted to use Greta for the model, it seems to me that right now there is no Zero-inflated Poisson distribution available in Greta. So I added one. I hope that other users who might want to use Zero-inflated Poisson distribution for their models could easily do so with Greta. I am very new to package contribution so I welcome any feedbacks. Thank you very much.

`
## Attach library
library(greta)
library(rethinking)

## Data for the model
#define parameters
prob_drink <- 0.2 # 20% of days
rate_work <- 1    # average 1 manuscript per day for Poisson model part

#sample one year of production
N <- 365
#simulate days monks drink
drink <- rbinom( N , 1 , prob_drink )
#simulate manuscripts completed
y <- (1-drink)*rpois( N , rate_work)

## Greta model
#prior
log_rate <- normal(0, 10)
logit_drink <- normal(0, 1)
rate <- exp(log_rate)
drink <- ilogit(logit_drink)

#likelihood
distribution(y) <- zero_inflated(drink, rate) 

#model
m <- model(logit_drink, log_rate)

#plot
plot(m)

#samples
samples <- mcmc(m)

#summary
summary(samples)

## McElreath code, Stan model
m11.4 <- map(
  alist(
    y ~ dzipois( p , lambda ),
    logit(p) <- ap,
    log(lambda) <- al,
    ap ~ dnorm(0,1),
    al ~ dnorm(0,10) ),
  data=list(y=y) )

#Stan results
precis(m11.4)

`

### CODE REVIEW

**Comment by goldingn** [comment]
That's awesome, thank you!

Yes, a zero-inflated Poisson would be a really useful thing to have. However, since it is a non-standard distribution, I'm not sure the main greta package is the right place for it. I'm trying to keep down the number of functions in the main package so that the interface doesn't become too unwieldy for beginners, and put more specialist functionality in packages that can be loaded when needed. Having this in another package would also mean we could provide decent documentation for it. For the rest of the distributions in the base greta package, we can just link to the helpfiles for the distributions in `stats` (or some other package), and then mirror all of the argument names. For this I think we'd need details to explain the type of zeroinflation being used etc.

I'm planning to rename and fix up [`greta.multivariate`](https://github.com/goldingn/greta.multivariate) to something like `greta.distributions` and then use that as a place for things like this. When I do, I can move this over. though it'll probably be a few months before I have time to get to that.

Here are some things that will need to be done before we can release this there:

- add documentation
- add an example
- make sure it works with tensorflow's broadcasting and batch dimension
- see whether the log density calculation can be made more efficient/numerically-stable
- use the representations mechanism to make use of the log of lambda, if available
- add tests to ensure:
	- the density is correct (matches a reference implementation) - [example](https://github.com/greta-dev/greta/blob/master/tests/testthat/test_distributions.R#L3-L13)
	- the densities are correct in array form - [example](https://github.com/greta-dev/greta/blob/master/tests/testthat/test_distributions.R#L15-L27)
	- that it can be used in models - examples [1](https://github.com/greta-dev/greta/blob/master/tests/testthat/test_distributions.R#L475-L478) [2](https://github.com/greta-dev/greta/blob/master/tests/testthat/test_distributions.R#L516) [3](https://github.com/greta-dev/greta/blob/master/tests/testthat/test_distributions.R#L554-L556) [4](https://github.com/greta-dev/greta/blob/master/tests/testthat/test_distributions.R#L600)
	- that it can be sampled from - [example](https://github.com/greta-dev/greta/blob/master/tests/testthat/test_distributions.R#L695)

Just to be clear, I'm not expecting you to do this @Rosenguyen0411 (though I'd be very happy to help if you'd like to give it a go), this is a to-do list for me to come back to. I really appreciate your taking the time to write this code send a PR!

**Comment by Rosenguyen0411** [comment]
Hi Nick,
Thank you so much for your response!
Yes, I would like to give it a try. However, I have a question: How should I add the documents and the tests? For the documents I believe I can attach R files. However, for the tests should I make another pull request for them? 
Sorry I am very new to package contribution. I was just using the ZIP distribution for my research and my Phd advisor (who is also a contributor to Greta @flyaflya) advised me to make a pull request cuz he thinks others might need to use the distribution as well.
Again, thank you for your response and I am also looking forward to future changes in Greta.

**Comment by goldingn** [comment]
OK great!

Probably the easiest thing to do would be open a new pull request to the `goldingn/greta.multivariate` repo instead. So clone that repo and put your new code in its own R file just like [this one]( https://github.com/goldingn/greta.multivariate/blob/master/R/conditional_bernoulli.R). That way you can write the documentation in roxygen (the `#'` marks you see) in that file. [Here's a guide](http://r-pkgs.had.co.nz/man.html) to documenting things with that system.

There's no test folder in there yet. But you could add one with [this function](https://usethis.r-lib.org/reference/use_testthat.html) from the `usethis` package.

**Comment by goldingn** [comment]
closing this, and hoping you can PR to the other repo as suggested!

**Pull request closed without merging**
