### PR TITLE
Only config reticulate 357

### PR DESCRIPTION
**Pull request by njtierney**
This PR initially worked on just using the `config/reticulate` approach, but it seems that we actually don't want to do that anymore, since we cannot control the python version. 

Instead, this approach should mean that we just provide a more concise method for installation of dependencies, as well as load these into a custom environment.

Some additional notes from @goldingn 's PR:

Some tweaks to tidy up the installation process.

```r
# wipe out the good environment
library(reticulate)
conda_remove("greta-env")
env <- tempfile("python-env-")
conda_create(env)
use_condaenv(env, required = TRUE)
reticulate::py_discover_config()

# try to run greta
library(greta)
x <- normal(0, 1)

# run this, as requested
create_conda_greta_env()

# <restart here> as requested
library(greta)
x <- normal(0, 1)
m <- model(x)
draws <- mcmc(m)

# wahoo!
```

This also installs miniconda if they don't already have it. NB if you run `reticulate::install_miniconda()` when you already have miniconda in the usual location, you end up with two conda installations which can be awkward. That shouldn't be an issue for greta users though.

If we can work out at which stage Python is initialised, we may be able to do away with the need to restart. That's not critical though.

It would also be cool if we could capture all the conda installation text, suppress during installation (replacing with our own shorter messages on progress), but make available to the user on completion if needed ('run `installation_messages()` to get all outputs for debugging purposes').

Note: this would be expected to work on CI, since I don't check that they are using the greta-env conda environment. That only gets forced if they don't have a working installation already. That also means advanced users can install their own set up in a different environment if they want!

### CODE REVIEW

**Comment by njtierney** [comment]
In addition, this PR could add some nice helper UI features from usethis, which look really nice:

E.g., similar to:

image

This looks nice and clean and since usethis is quite popular now seeing this will be familiar as well.

**Comment by goldingn** [comment]
Another thought: we should rename the function that installs this stuff. We're currently using the function called create_greta_env(), but it does more than that. So install_greta_deps() should probably contain all that code.

**Comment by njtierney** [comment]
OK so some todo's

- [ ] Move installation things from `create_greta_env()` into `install_greta_deps()`
- [ ] Document potential issues regarding installing miniconda - "If you run reticulate::install_miniconda() when you already have miniconda in the usual location, you end up with two conda installations, which can be awkward"
- [ ] Can we work out at which stage Python is initialised, as this may mean we can ignore needing to restart (not critical)
- [ ] Capture conda installation text and suppress during installation 
- [ ] Replace conda installation test with our own shorter messages on progress
- [ ] Make conda installation text available to the user on completion if needed (with a "run `installation_messages()` to get all outputs for debugging purposes" note).
- [ ] Document any extra things about the greta env somewhere. E.g., advanced users can install their own set up in a different environment if they want!

**Comment by njtierney** [comment]
@goldingn does this mean we need to replace:

https://github.com/greta-dev/greta/pull/416/files?file-filters%5B%5D=.R&file-filters%5B%5D=.Rd#diff-c48a0a9ba78f19920b59584d9488e7dcb6449cb7a074d9da170ef315d6b5864bR31-R37

with `install_greta_deps()` ?

**Comment by njtierney** [comment]
The current state of play:

`install_greta_deps()` does the following:

- If it is windows, do the following:
    - use conda as installation method
    - find conda binary
    - if there isn't a conda binary, tell user where to install anaconda
    - if python is available, provide instructions on how to call `install_greta_deps` in a fresh session without TF or co initialised
- Use `tensorflow::install_tensorflow()` to install TF version 1.14, tf-probability 0.7.0, and numpy 1.16.4

And `create_conda_greta_env()` does;

- install miniconda if needed
- create the greta conda environment with the required version of python with `reticulate::conda_create()`
- Creates the relevant python packages into the conda environment, named `greta-env`, using `reticulate::conda_install()`, and uses "numpy==1.16.4", "tensorflow-probability==0.7.0", "tensorflow==1.14.0"

So based on @goldingn 's advice above, we move

```

  # install the relevant python packages into the conda environment, using pip
  reticulate::conda_install(
    envname = "greta-env",
    packages = c("numpy==1.16.4",
                 "tensorflow-probability==0.7.0",
                 "tensorflow==1.14.0")
    # pip = TRUE
  )
```

From `create_conda_greta_env()` into `install_greta_deps()`, replacing:


```
install_tensorflow(
    method = method,
    conda = conda,
    version = "1.14.0",
    extra_packages = c("tensorflow-probability==0.7.0, numpy==1.16.4"),
    pip_ignore_installed = FALSE,
    ...
  )
```

**Comment by njtierney** [comment]
OK so doing that didn't work, need to roll back and test locally.

**Comment by goldingn** [comment]
I wasn't suggesting we have both functions, just one. The function body of `create_greta_env()` , but rename it `install_greta_deps()` since that's a clearer name for the user. So delete the previous `install_greta_deps()` function file.

That way users can just run that one function and it will do everything for them, and every time it is loaded, greta will find and use that environment.

Though I haven't had time to keep up with your recent commits, so I may have missed some flaw in that plan!

**Comment by njtierney** [comment]
No, you didn't miss a part of my plan, I just misread what you said! Will get on that now. :)

**Comment by njtierney** [comment]
Somewhat confusingly, this PR is now out of date and replaced by #417

**Pull request closed without merging**
