### PR TITLE
first draft of greta_sitrep() for loading greta and establishing if t…

### PR DESCRIPTION
**Pull request by njtierney**
…he software is ready to use

See #441 for linked issue.

It currently looks something like this:

image

Although I'm not 100% sure why "loaded Tensorflow 1.14.0" appears in the middle of the text.

I'm not 100% if it should initialise Python, and I need to test out how it fails in specific situations and what sort of instructions appear. For example, it should be OK if users don't want to use a greta conda env.

To do that I'll need to write some mocking tests, I think?

@goldingn do you have any thoughts on how this is presented and if this is useful? Do you think that a separate, `load_greta_deps()` or similar function should be used to load and establish Python (instead of needing to run greta code to trigger that step)

### CODE REVIEW

**Comment by goldingn** [comment]
This looks helpful! I think the initialisation is good. And necessary to make sure everything works.

Should the version numbers for TF and TFP be reported when saying what is available, to reiterate the requuirement and what is checked?

**Comment by njtierney** [comment]
Yup, agree! Having thinking about this a bit more this past week I think a few more helpers on what to do  if each part isn't installed are there. So overall:

- [ ] report the version numbers of each of TF, TFP, Python
- [ ] if there is an error, report where things do not match (e.g., TF not found, or TF installed is not the right version)
- [ ] provide information on what to do in the case that each of these things isn't found (most likely that would be to just run `install_greta_deps()`

**Comment by njtierney** [comment]
This is what it currently looks like:

image

Note this also removes the errant "Loaded Tensorflow 1.14.0" message as well.

**Comment by njtierney** [comment]
reduced exclamation marks

image

**Comment by njtierney** [comment]
Added mocking tests for different versions of software and software availability

**Pull request merged**
