### PR TITLE
add method for kronecker product of greta_array objects

### PR DESCRIPTION
**Pull request by jdyen**
Added an internal tf_kronecker function and a wrapper to dispatch through base::kronecker. Added test to matrix functions in tests_functions.R

### CODE REVIEW

**Comment by jdyen** [comment]
annoying -- sorry. The tests ran fine locally.

**Comment by jdyen** [comment]
the dispatch isn't working correctly -- it's going to .kronecker() rather than the greta_array version of this function. Doesn't do this locally.

**Comment by jdyen** [comment]
This could not have been more convoluted. Sorry.

**Comment by goldingn** [comment]
Hurrah! Thanks Jian, I'll review next week.

**Comment by goldingn** [comment]
Thanks Jian!

Looks great. New features get merged onto the dev branch, so I've switched that over and cleared up the one conflict. Once that passes checks, I'll do a squash and merge which will roll of these commits into one. That might break your fork a bit, but I can help resolve that if it does!

**Pull request merged**
