### PR TITLE
check that tf is installed when calling `greta_array`

### PR DESCRIPTION
**Pull request by njtierney**

### CODE REVIEW

**Comment by goldingn** [comment]
Should redundant calls to this function in other places be removed?

**Comment by njtierney** [comment]
That's a good idea!

I was just trying to work out how to test this behaviour as well, but I think it ends up being slightly tricky to test in testthat.

**Comment by njtierney** [comment]
I'm not sure what the overall benefit would be of removing the redundant calls at the moment? It doesn't seem to add much extra overhead time? 

Although I agree it would be a good thing to only test when strictly necessary, I'm not sure the incremental gain is worth it?

**Comment by goldingn** [comment]
Just cleanliness, though since it is hard to test probably safer to leave
it!

**Comment by njtierney** [comment]
> Just cleanliness, though since it is hard to test probably safer to leave it!

Yup - agree that it would be cleaner, but might be safer to leave it for the moment.

Current tests aren't failing more than master.

**Pull request merged**
